aplus/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('aplus_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplus_app/staff/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home', home, name="staff_home"),
    path('students', students, name="staff_students"),
    path('room/<str:room_id>', room, name="staff_room"),
    path('reward_plus_1/<str:student_id>&<str:room_id>', reward_plus_1, name="staff_reward_plus_1"),
    path('student/<str:student_id>', student, name="staff_student"),
    path('open_room/<str:room_id>', open_room, name="staff_open_room"),
    path('close_room/<str:room_id>', close_room, name="staff_close_room"),
    path('rooms', rooms, name="staff_rooms"),
    path('login', login, name="staff_login"),
    path('logout', logout, name="staff_logout"),
    path('add_course', add_course, name="staff_add_course"),
    path('add_room', add_room, name="staff_add_room"),
]

aplus_app/student/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home', home, name="student_home"),
    path('course/<str:course_id>', course, name="student_course"),
    path('login', login, name="student_login"),
    path('logout', logout, name="student_logout"),
    path('signup', signup, name="student_signup"),
    path('login_cause_by_qr/<str:room_id>', login_cause_by_qr, name="student_login_cause_by_qr"),
    path('register_course', register_course, name="student_register_course"),
    path('attend_room', attend_room, name="student_attend_room"),
]

aplus_app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .student import views as student_views
from .views import index

urlpatterns = [
    path('', index, name="app_index"),
    path('staff/', include('aplus_app.staff.urls')),
    path('student/', include('aplus_app.student.urls')),
    path('qrcode/attend/<str:room_id>', student_views.attend_room_with_qrcode, name='attend_room_with_qrcode')
]

aplus_app/models.py
import random
import string
from io import BytesIO
import os
from django.db import models
import qrcode as qrc
from django.http import HttpResponse
from django.core.files import File
from django.conf import settings


def rgen(l):
    letter = string.ascii_uppercase
    u = "".join(random.choice(letter) for i in range(l))
    return u


def rint(l):
    num = ""
    for i in range(l):
        number = random.randint(0, 9)
        num = num + str(number)
    return num


class Staff(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    gender = models.CharField(max_length=10, default="male")
    password = models.TextField()
    img = models.ImageField(upload_to="staff/imgs")

    def add_room(self, name, group_id, course_id, host):
        room_id = ""
        if Course.objects.get(pk=course_id).room_set.all().count() == 0:
            room_id = str(f"{rgen(4)}{course_id[2:]}1")
        else:
            room_id = str(
                f"{rgen(4)}{course_id[2:]}{Course.objects.get(pk=course_id).room_set.all().count() + 1}{rgen(1)}")

        qr = qrc.QRCode(
            version=1,
            error_correction=qrc.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        data_link = f"http://{host}/qrcode/attend/{room_id}"
        qr.add_data(data_link)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")

        media_dir = os.path.join(settings.MEDIA_ROOT, 'qrcodes')
        if not os.path.exists(media_dir):
            os.makedirs(media_dir)

        file_path = os.path.join(media_dir, f"qr{room_id}.png")
        img.save(file_path)

        new_room = Room(
            id=room_id,
            name=name,
            group=Group.objects.get(pk=group_id),
            course=Course.objects.get(pk=course_id),
            status="Closed",
            qrcode=file_path,
            key=rint(7)
        )

        new_room.save()

    def add_course(self, name, recommended_level, description):
        course_id = ""
        if Course.objects.all().count() == 0:
            course_id = "1"
        else:
            course_id = int(list(Course.objects.all())[-1].id[2:]) + 1
        new_course = Course(
            name=name,
            recommended_level=recommended_level,
            description=description,
            id=str(f"CS{course_id}"),
            lecturer=self
        )

        new_course.save()

    def get_recent_rooms(self, number):
        rooms = Room.objects.filter(course__lecturer=self).order_by('-date')
        return rooms[:number]

    def reward_student(self, student: 'Student', room: 'Room'):
        score = Score.objects.filter(room=room).get(student=student)
        score.score += 1
        score.save()


class Course(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    recommended_level = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    lecturer = models.ForeignKey(Staff, on_delete=models.CASCADE)
    registered_students = models.JSONField(default={"data": []})

    def add_student(self, student):
        self.registered_students["data"].append(student)
        self.save()

    def get_total_students(self):
        return len(self.registered_students['data'])

    def has_student(self, student: 'Student'):
        if student.id in self.registered_students['data']:
            return True
        else:
            return False

    def get_student_attendance(self, student: 'Student'):
        total_attendance = 0
        total_room = student.group.room_set.filter(course=self)
        for room in total_room:
            if student.id in room.attendants["data"]:
                total_attendance += 1
        return str(f"{total_attendance}/{total_room.count()}")


class Group(models.Model):
    name = models.CharField(max_length=100)


class Room(models.Model):
    name = models.CharField(max_length=100)
    id = models.CharField(max_length=100, primary_key=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    status = models.CharField(max_length=20)
    attendants = models.JSONField(default={"data": []})
    date = models.DateField(auto_now=True)
    key = models.TextField(default="123456")
    qrcode = models.ImageField(upload_to="qrcodes", default="qrcodes/default", blank=True, null=True)

    def add_attendant(self, student: 'Student'):
        print(self.course.has_student(student))
        log = {}
        if self.status == "Open":
            if student.id in self.attendants['data']:
                log = {
                    "code": 2,
                    "msg": "Already Attend",
                }
                pass
            else:
                if self.course.has_student(student):
                    if student.group == self.group:
                        self.attendants['data'].append(student.id)
                        self.save()
                        new_score = Score(
                            score=1.0,
                            room=self,
                            student=student,
                        )
                        new_score.save()
                        log = {
                            "code": 1,
                            "msg": "Attend Successful",
                        }
                    else:
                        log = {
                            "code": 0,
                            "msg": "Failed! You are not in the required group",
                        }
                else:
                    log = {
                        "code": 0,
                        "msg": "Failed! You are not registered to the course",
                    }
        else:
            log = {
                "code": 0,
                "msg": "Failed! Room is Closed",
            }

        return log

    def get_attendants(self):
        attendants = []
        for _id in self.attendants['data']:
            attendant = Student.objects.get(pk=_id)
            attendants.append(attendant)

        return attendants

    def get_attendance_count(self):
        return len(self.get_attendants())

    def open_room(self):
        self.status = "Open"
        self.save()

    def close_room(self):
        self.status = "Closed"
        self.save()

    def has_student(self, student: 'Student'):
        if student.id in self.attendants['data']:
            return True
        else:
            return False


class Student(models.Model):
    name = models.CharField(max_length=100)
    id = models.CharField(max_length=20, primary_key=True)
    level = models.CharField(max_length=20)
    group = models.ForeignKey(Group, on_delete=models.SET_DEFAULT, default=5)
    password = models.TextField()

    def get_unregistered_courses(self):
        unregistered_courses = []
        for i in Course.objects.all():
            if self.id in i.registered_students["data"]:
                pass
            else:
                unregistered_courses.append(i)

        return unregistered_courses

    def get_registered_courses(self):
        registered_courses = []
        for i in Course.objects.all():
            if self.id in i.registered_students["data"]:
                registered_courses.append(i)
            else:
                pass

        return registered_courses

    def get_attendance(self, course: 'Course'):
        rooms = Room.objects.filter(course=course).filter(group=self.group)
        attend_count = 0
        for room in rooms:
            if self.id in room.attendants["data"]:
                attend_count += 1
        course_rooms_count = Room.objects.filter(course=course).filter(group=self.group).count()
        return str(f'{attend_count}/{course_rooms_count}')

    def get_recent_rooms(self, number):
        rooms = Room.objects.filter(group=self.group).order_by('-date')
        return rooms[:number]

    def get_room_score(self, room: 'Room'):
        score = Score.objects.filter(room=room).get(student=self).score
        return score

    def get_course_score(self, course: 'Course'):
        scores = Score.objects.filter(room__course=course).filter(student=self)
        score = 0
        for _score in scores:
            score = score + _score.score
        return score


class Score(models.Model):
    score = models.FloatField()
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

aplus_app/student/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from ..models import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages


def home(request):
    try:
        if request.session["active_student_id"] == "":
            return redirect("student_login")
    except KeyError:
        request.session["active_student_id"] = ""
        return redirect("student_home")

    try:
        active_student = Student.objects.get(pk=request.session["active_student_id"])
        context = {
            "me": active_student,
            "me_name_0": active_student.name[0],
            "attend_attempt_log": request.session["attend_attempt_log"]
        }
        request.session["attend_attempt_log"] = {}
        return render(request, 'aplus_app/student/home.html', context)
    except ObjectDoesNotExist:
        request.session["active_student_id"] = ""
        return redirect("student_home")


def login(request):
    if request.method == "POST":
        student_id = request.POST['id']
        password = request.POST['password']

        try:
            student = Student.objects.get(pk=student_id)
            if password == student.password:
                request.session['active_student_id'] = student_id
                return redirect("student_home")
            else:
                request.session['active_student_id'] = ""
                return HttpResponse("Invalid Logins")
        except ObjectDoesNotExist:
            request.session['active_student_id'] = ""
            return HttpResponse("UNKOWN")

    return render(request, "aplus_app/student/login.html")


def logout(request):
    request.session["active_student_id"] = ""
    return redirect("student_home")


def signup(request):
    context = {
        "groups": Group.objects.all()
    }
    if request.method == "POST":
        student_id = request.POST['id']
        full_name = request.POST['full_name']
        level = request.POST['level']
        group_id = request.POST['group_id']
        password = request.POST['password']

        try:
            student = Student.objects.get(pk=student_id)
            return HttpResponse("Student Already Exist")
        except ObjectDoesNotExist:
            new_student = Student(
                id=student_id,
                level=level,
                group=Group.objects.get(pk=group_id),
                password=password,
                name=full_name
            )

            new_student.save()
            request.session['active_student_id'] = student_id
            return redirect("student_home")

    return render(request, "aplus_app/student/signup.html", context)


def register_course(request):
    try:
        if request.session["active_student_id"] == "":
            return redirect("student_login")
    except KeyError:
        request.session["active_student_id"] = ""
        return redirect("student_home")

    try:
        active_student = Student.objects.get(pk=request.session["active_student_id"])
        if request.method == "POST":
            course_id = request.POST['course_id']
            course = Course.objects.get(pk=course_id)
            course.add_student(student=active_student.id)
            return redirect("student_home")
    except ObjectDoesNotExist:
        request.session["active_student_id"] = ""
        return redirect("student_home")


def attend_room(request):
    try:
        if request.session["active_student_id"] == "":
            return redirect("student_login")
    except KeyError:
        request.session["active_student_id"] = ""
        return redirect("student_home")

    try:
        active_student = Student.objects.get(pk=request.session["active_student_id"])
        if request.method == "POST":
            room_id = request.POST["room_id"]
            key = request.POST["key"]

            room = Room.objects.get(pk=room_id)

            if room.key == key:
                a = room.add_attendant(active_student)
                request.session["attend_attempt_log"] = {
                    "msg": a["msg"],
                    "code": a["code"]
                }
                return redirect("student_home")
            else:
                return HttpResponse("<b>Wrong Key</b>")

    except ObjectDoesNotExist:
        request.session["active_student_id"] = ""
        return redirect("student_home")


def attend_room_with_qrcode(request, room_id):
    try:
        if request.session["active_student_id"] == "":
            return redirect("student_login_cause_by_qr", room_id=room_id)
    except KeyError:
        request.session["active_student_id"] = ""
        return redirect("student_login_cause_by_qr", room_id=room_id)

    try:
        active_student = Student.objects.get(pk=request.session["active_student_id"])
        room = Room.objects.get(pk=room_id)
        a = room.add_attendant(active_student)
        request.session["attend_attempt_log"] = {
            "msg": a["msg"],
            "code": a["code"]
        }
        return redirect("student_home")

    except ObjectDoesNotExist:
        request.session["active_student_id"] = ""
        return redirect("student_login_cause_by_qr", room_id=room_id)


def login_cause_by_qr(request, room_id):
    context = {
        "room_id": room_id,
        "room": Room.objects.get(pk=room_id)
    }
    if request.method == "POST":
        student_id = request.POST['id']
        password = request.POST['password']

        try:
            student = Student.objects.get(pk=student_id)
            if password == student.password:
                request.session['active_student_id'] = student_id
                return redirect('attend_room_with_qrcode', room_id=room_id)
            else:
                request.session['active_student_id'] = ""
                return HttpResponse("Invalid Logins")
        except ObjectDoesNotExist:
            request.session['active_student_id'] = ""
            return HttpResponse("UNKOWN")

    return render(request, "aplus_app/student/login_cause_by_qr.html", context)


def course(request, course_id):
    try:
        if request.session["active_student_id"] == "":
            return redirect("student_login")
    except KeyError:
        request.session["active_student_id"] = ""
        return redirect("student_home")

    try:
        active_student = Student.objects.get(pk=request.session["active_student_id"])
        _course = Course.objects.get(pk=course_id)
        context = {
            "me": active_student,
            "me_name_0": active_student.name[0],
            "course": _course
        }
        request.session["attend_attempt_log"] = {}
        return render(request, 'aplus_app/student/course.html', context)
    except ObjectDoesNotExist:
        request.session["active_student_id"] = ""
        return redirect("student_home")

aplus_app/views.py
from django.shortcuts import render


def index(request):
    request.session["attend_attempt_log"] = {}
    return render(request, 'aplus_app/index.html')

aplus_app/templates/aplus_app/staff/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'aplus_app/fa/allicons.css' %}">

<header class="grid-header">
      <div class="logo">
          <div onclick="openNav('lnd')">
              <i class="fa-thin fa-bars" style="color:white"></i>
          </div>
          <div>
              <b style="font-size:20px; color:white; margin-right:30px">A<sup>+</sup></b>
              <span style="color:gold; border-radius: 6px; padding: 6px; border:1px solid gold;">Demo</span>
          </div>
      </div>
      <div class="mid-div">
              <div class="nav-btn" onclick="window.open('{% url 'staff_home' %}', '_self')">
                  <i class="fa-thin fa-gauge"></i>
                  <span>Dashboard</span>
              </div>
            <div class="nav-btn" onclick="window.open('{% url 'staff_rooms' %}', '_self')">
                  <i class="fa-thin fa-school"></i>
                  <span>Rooms</span>
            </div>
          <div class="nav-btn" onclick="window.open('{% url 'staff_students' %}', '_self')">
                      <i class="fa-thin fa-users"></i>
                     <span>Students</span>
              </div>
      </div>
      <div class="right">
          <div class="dropdown" style="float:left;">
              <div class="avatar">
                {{staff_name_0}}
              </div>
              <div style="left: -113px; top: 39px;" class="dropdown-content">
                <a href="#"><i class="fa-regular fa-user"></i><span>Profile</span></a>
                <a href="{% url 'staff_logout' %}"><i class="fa-regular fa-right-from-bracket"></i><span>Logout</span></a>
              </div>
            </div>
      </div>
</header>



<LeftNavDrawer id="lnd">
            <NavListItems>
                <ListItem onclick="window.open('{% url 'staff_home' %}', '_self')">
                    <Icon><i class="fa-light fa-gauge   "></i></Icon>
                    <Name>Dashboard</Name>
                </ListItem>
                <ListItem onclick="window.open('{% url 'staff_rooms' %}', '_self')">
                    <Icon><i class="fa-light fa-school"></i></Icon>
                    <Name>Rooms</Name>
                </ListItem>
                <ListItem onclick="window.open('{% url 'staff_students' %}', '_self')">
                    <Icon><i class="fa-light fa-users"></i></Icon>
                    <Name>Students</Name>
                </ListItem>
            </NavListItems>
        </LeftNavDrawer>

aplus_app/templates/aplus_app/staff/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load staff_ui %}
{% load head_tag %}

{% html_head_tag title="A+|Staff Home" %}

<body>
{% staff_app_navs active="home" %}
<div onclick="closeForm(b=['form-admin'])" id="body-cover"></div>
<div class="form-div" id="form-admin">
    <div class="header">
        <h4>Add Course</h4>
    </div>
    <div></div>

        <br><br>
    <form method="post" action="{% url 'staff_add_course' %}">
    {% csrf_token %}

    <input name="name" type="text" placeholder="Course Name" required/><br><br>
    <input name="description" type="text" placeholder="Description" required/><br><br>
    <input name="rec_level" type="text" placeholder="Recommended Level" required/><br><br>

    <input type="submit" value="Submit">
</form>

   </div>

<div onclick="closeNav('lnd')" id="nav-wrapper"></div>
<div style="margin-top: 90px"></div>

<div  class="cont-090">
        <h2 style="margin: 0 0 20px 30px">Welcome Back <i class="fa-solid fa-smile"></i></h2>
        <h1 style="margin: 0 0 20px 30px">Mr. {{staff.name}}</h1>
</div><br><br>
<div class="cont-898">
        <h3 style="margin: 0 0 20px 30px">My Courses <span onclick="openForm('form-admin')" style="float: right; font-size:17px; cursor:pointer">Add Course</span></h3>
        <hr><BR>
</div>
<div class="cont-898-1">
    <div style="display:block; margin: 0 0 0 30px"></div>
            {% for course in staff.course_set.all %}
                <div class="course">
                    <span><b>Course ID:</b> {{course.id}}</span>
                    <span><b>Course Name:</b> {{course.name}}</span>
                    <span><b>Course Name:</b> {{course.get_total_students}}</span>
                </div>
            {% empty %}
                <span>No course</span>
            {% endfor %}
    <div style="display:block; margin: 0 30px 0 0px"></div>
</div>


        <div style="display:block; margin: 280px 0 0 30px"></div>

</body>
<script src="{% static 'aplus_app/js/bodycover.js' %}"></script>
<script src="{% static 'aplus_app/js/process.js' %}"></script>
</html>

aplus_app/templates/aplus_app/staff/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
 <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <link rel="stylesheet" href="{% static 'aplus_app/css/page.css' %}">
     <link rel="stylesheet" href="{% static 'aplus_app/css/ananse.css' %}">
     <link rel="stylesheet" href="{% static 'aplus_app/css/main.css' %}">
     <link rel="stylesheet" href="{% static 'aplus_app/css/form.css' %}">
     <link rel="stylesheet" href="{% static 'aplus_app/fa/allicons.css' %}">
    <title>Staff|Login</title>
</head>
<body>
<video class="body-vid" autoplay="true" loop="true" muted>
    <source src="{% static 'aplus_app/vids/ani1.mp4' %}" type="video/mp4">
</video>
<div class="alt-body">
    <div class="form-cont">
        <form method="post" action="{% url 'staff_login' %}">
            {% csrf_token %}
            <div class="head">Staff Login</div>
            <div class="form-inputs">
                <input type="text" name="id" placeholder="Staff ID">
                <input type="password" name="password" placeholder="Password">
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>
</div>
<div class="alt-logo fa-bounce">A<sup>+</sup>&nbsp;&nbsp;<span style="color:gold; border-radius: 6px; padding: 6px; border:1px solid gold; font-size:20px">Demo</span></div>

</body>
</html>

aplus_app/templates/aplus_app/staff/rooms.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load staff_ui %}
{% load head_tag %}
{% load custom_filters %}

{% html_head_tag title="A+|Staff Home" %}

<body>
{% staff_app_navs active="home" %}

       <div onclick="closeNav('lnd')" id="nav-wrapper"></div>

<div onclick="closeForm(b=['form-admin'])" id="body-cover"></div>
<div class="form-div" id="form-admin">
    <div class="header">
        <h4>Add Room</h4>
    </div>
    <div></div>

        <br><br>
    <form method="post" action="{% url 'staff_add_room' %}">
    {% csrf_token %}

    <input name="name" type="text" placeholder="Room Name, Example: Lecture 1, Hardware" required/><br><br>
    <select name="group_id">
        <option>Room for Group</option>
        {% for group in groups %}
            <option value="{{group.id}}">{{group.name}}</option>
        {% endfor %}
    </select>
        <select name="course_id">
            <option>Select Course</option>
            {% for course in staff.course_set.all %}
                <option value="{{course.id}}">{{course.name}}</option>
            {% endfor %}
        </select>
<br>
<div></div><br>
    <input type="submit" value="Submit">
</form>

   </div>





<div style="margin-top: 90px"></div>

<div class="cont-090">
        <h3 style="margin: 0 0 20px 20px">Tip <i class="fa-solid fa-info-circle"></i></h3>
        <div style="margin: 0 0 20px 20px">
            Please add a room as soon as you begin a lecture session and close immediately when done.
        </div>
    <div style="margin: 0 0 20px 20px">
            This is to ensure that only student available during that sessions can mark their attendance
    </div>
</div><br>
<div class="cont-898">
       <h3 style="margin: 0 0 20px 30px">Recent Rooms <span onclick="openForm('form-admin')" style="float: right; font-size:17px; cursor:pointer">Add Room</span></h3>
        <hr>
</div>
<div class="cont-898">
    <select id="group_select">
    <option id="all_student_opt">All</option>
    {% for group in groups %}
        <option id="{{group.id}}">{{group.name}}</option>
    {% endfor %}
    </select>
    <select id="course_select">
    <option id="any_course_opt">Any</option>
    {% for course in staff.course_set.all %}
        <option id="{{course.id}}">{{course.name}}</option>
    {% endfor %}
    </select>
    <br><div></div>
</div>
<div class="cont-898-1">
    <div style="display:block; margin: 0 0 0 30px"></div>
    <div class="custom-table-001">
        <div class="row-head">
            <div class="cell"><b>Room Name</b></div>
            <div class="cell"><b>ID</b></div>
            <div class="cell"><b>N<u>o</u> Attendance</b></div>
            <div class="cell"><b>Group</b></div>
            <div class="cell"><b>Course</b></div>
            <div class="cell"><b>Status</b></div>
            <div class="cell"><b>Date</b></div>
        </div>
        {% for room in staff|get_recent_rooms:5 %}
        <div class="row" onclick="window.open('{% url 'staff_room' room_id=room.id %}', '_self')">
            <div class="cell">{{ room.name }}</div>
            <div class="cell">{{ room.id }}</div>
            <div class="cell">{{ room.get_attendance_count }}</div>
            <div class="cell">{{ room.group.name }}</div>
            <div class="cell">{{ room.course.name }}</div>
            <div class="cell">{{ room.status }}</div>
            <div class="cell">{{ room.date }}</div>
        </div>
        {% endfor %}
    </div>
    <div style="display:block; margin: 0 30px 0 0px"></div>
</div>
       <div style="display:block; margin: 280px 0 0 30px"></div>
</body>
<script src="{% static 'aplus_app/js/bodycover.js' %}"></script>
<script src="{% static 'aplus_app/js/process.js' %}"></script>

<script>
    // Function to filter the table based on selected options
    function filterTable() {
        // Get selected values from the dropdowns
        const selectedGroup = document.getElementById("group_select").value;
        const selectedCourse = document.getElementById("course_select").value;

        // Get all rows in the table (excluding the header row)
        const rows = document.querySelectorAll(".custom-table-001 .row");

        // Loop through each row and check if it matches the selected filters
        for (const row of rows) {
            const groupCell = row.querySelector(".cell:nth-child(4)").textContent.trim();
            const courseCell = row.querySelector(".cell:nth-child(5)").textContent.trim();

            // Hide the row if it doesn't match the selected filters
            if ((selectedGroup !== "All" && groupCell !== selectedGroup) ||
                (selectedCourse !== "Any" && courseCell !== selectedCourse)) {
                row.style.display = "none";
            } else {
                row.style.display = "flex";
            }
        }
    }

    // Attach event listeners to the select elements
    const groupSelect = document.getElementById("group_select");
    const courseSelect = document.getElementById("course_select");

    groupSelect.addEventListener("change", filterTable);
    courseSelect.addEventListener("change", filterTable);

    // Initially, call the filterTable function to show the default selected options
    filterTable();
</script>

</html>

aplus_app/templates/aplus_app/staff/student.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load staff_ui %}
{% load head_tag %}
{% load custom_filters %}

{% html_head_tag title="A+|Staff Home" %}
<body>
{% staff_app_navs active="home" %}

       <div onclick="closeNav('lnd')" id="nav-wrapper"></div>
<div onclick="closeForm(b=['qrcode-div'])" id="body-cover"></div>
<div class="form-div larger" id="qrcode-div">
    <div class="header">
        <div>Scan QR code to mark your attendance</div>
    </div>
    <div style="margin: -20px 0 0 0">
        <div>Or Use Key: <h2>{{room.key}}</h2></div>
    </div>
    <div>
        <img src="/media/{{room.qrcode}}">
    </div>
   </div>



<div style="margin-top: 90px"></div>
<div class="cont-090">
        <div style="margin: 0 0 20px 30px; font-size:20px">Student &nbsp;&nbsp;<i class="fa-solid fa-user"></i></div>
        <h1 style="margin: 0 0 20px 30px">Mr. {{student.name}}</h1>
</div>
<div  class="cont-090">
        <div style="margin: 0 0 10px 20px">
            <b>Student Name:</b> {{student.name}}
        </div>
        <div style="margin: 0 0 10px 20px">
            <b>Index number:</b> {{student.id}}
        </div>
        <div style="margin: 0 0 10px 20px">
            <b>Group:</b> {{student.group.name}}
        </div>
        <div style="margin: 0 0 10px 20px">
            <b>Level</b>: {{student.level}}
        </div>
</div><br>

<div class="cont-898">
        <h3 style="margin: 0 0 20px 30px">Registered Courses (My courses)</h3>
        <hr><BR>
</div>

{% for course in staff.course_set.all %}
    {% if course|course_has_student:student %}
        <div  class="cont-090">
            <div style="margin: 0 0 20px 20px"><b>Course</b> &nbsp;&nbsp;<i class="fa-solid fa-book"></i></div>

            <div style="margin: 0 0 10px 20px">
                <b>Name:</b> {{ course.name }}
            </div>
            <div style="margin: 0 0 10px 20px">
                <b>Attendance:</b> {{course|get_student_attendance:student}}
            </div>
            <div style="margin: 0 0 10px 20px">
                <b>Total Points:</b> {{student|get_course_score:course}}
            </div>

        </div><br>
    {% endif %}
{% endfor %}


        <div style="display:block; margin: 280px 0 0 30px"></div>

</body>
<script src="{% static 'aplus_app/js/bodycover.js' %}"></script>
<script src="{% static 'aplus_app/js/process.js' %}"></script>


</html>